### ISSUE TITLE
Use `Date` object to process the dates

### ISSUE THREAD

**Issue by Ayesh** [sacsand/lanka-nic-2019#1]
Hi Sachintha,
Good job putting out the library. I maintain a similar PHP library (slwdc/NICParser), and I couldn't help but notice how bad things could go with the way this library handles dates. 

Processing date and time information is extremely hard, and I even have deliver talks on how _not_ to process dates [like this.](https://github.com/sacsand/lanka-nic-2019/blob/master/index.js#L6), which ignores leap year pattern (which is quite complicated). Ideally, the library should use the `Date()` object which can significantly make things easier. 

```js
id_number = '922601111v';
year = 1992; // This is 19 + /^(\d){2}/ or somehow the extracted year off the ID number
delta = 260; // This is the 3 digits after the year /^(?:\d){2}(\d){3}/

date = new Date(Date.UTC(year, 0, 1));
date.setDate(delta);

date.getUTCDate(); // 16
date.getUTCMonth(); // 8 for September because months are zero indexed.
```

This, and you can get rid of the hardcoded object with months and how many days each month has. I'd be happy to put together a PR if it helps, but I suppose this could look like I'm hijacking your library. 

Thanks.

**Comment by sacsand** [comment]
Hi Ayesh,
let me explain my logic,
 **Sri Lanka NIC ID originally generated assuming that February having 29 days, including non leaf years.That means  366 days per year.** 

   _example:_ 

      931260723v is the nic for who born in 05-05-1993  . 126 th day should be equal to May 5 1993
      but
     -> If we get the sum of  days from 1993 January 1 to May 5 = 31+28+31+30+5 =  125 
     -> So May 5 is 125th day ( this is the correct way according  world standard  )
     -> But in Sri Lankan NIC May 5 is taken as 126th day ( accordion to DRP  3 digit 
         after year is represent the  Birth day of the year,which is not clearly. but this how they have decided it in first place).
     -> This because DRP  considered February 29 as  a day even  in non leaf years.
      
   and if we get a nic number of a  person born on 31 dec 1993 .nic is   93366XXXXv . --  Birth day of the year is 366 - but 1993 have only 365 days.


**so the leaf year pattern was ignored from the beginning.** 



My logic is based on this scenario.So i have used hardcoded object with months to keep logic simple. If followed suggested way i may have to check for non leaf years and reduce 1 day and get the date , only reduce if it is after feb 28 like that ....etc..there could be many other approach .

i have  followed the test driven development for this library. Always got the expected output . 

**Did you got any unexpected output when your testing the library ?if please let me know .**


Thank You.

**Comment by Ayesh** [comment]
I had no idea that Sri Lankan NIC numbers always assumed 29 days days in February. I get it's probably for computational ease, but the Wikipedia article isn't technically accurate to say it's the day of the year. 

I suppose I should add a few more test cases to my library and double check. 

This comes down to personal preference though, but I still think there's no need to hardcode a Gregorian calendar, but it's apparently a problem in how our country runs.
